BoxLayout:
    orientation: 'vertical'
    padding: 5

    Label:
        text: "AK Sharma Programs"
        height: dp(10)
        size_hint: 1, 1
        font_size: 25

    BoxLayout:
        orientation: "horizontal"
        TextInput:
            id: expinp
            hint_text:"ex : 2+3*4"
            size_hint: 0.8, 1
            height: dp(7)

        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.2, 1
            Button:
                text: "="
                size_hint: 1, 0.5
                height: dp(7)
                on_release: app.calculate(expinp._get_text())
            Button:
                text:  "C"
                size_hint: 1, 0.5
                on_release: expinp._set_text ("")

    BoxLayout:
        orientation: 'horizontal'

        Button:
            text: "+"
            size_hint: 0.5,1
            on_release: expinp._set_text (expinp._get_text() + " + ")

        Button:
            text: "-"
            size_hint: 0.5,1
            on_release: expinp._set_text (expinp._get_text() + " - ")
                  
        Button:
            text: "÷"
            size_hint: 0.5,1
            on_release: expinp._set_text (expinp._get_text() + " ÷ ")   

    BoxLayout:
        orientation: 'horizontal'

        Button:
            text: "1"
            on_release: expinp._set_text (expinp._get_text() + "1")

        Button:
            text: "2"
            on_release: expinp._set_text (expinp._get_text() + "2")
                  
        Button:
            text: "3"
            on_release: expinp._set_text (expinp._get_text() + "3")

        Button:
            text: "X"
            on_release: expinp._set_text (expinp._get_text() + " X ")

    BoxLayout:
        orientation: 'horizontal'

        Button:
            text: "4"
            on_release: expinp._set_text (expinp._get_text() + "4")

        Button:
            text: "5"
            on_release: expinp._set_text (expinp._get_text() + "5")
                  
        Button:
            text: "6"
            on_release: expinp._set_text (expinp._get_text() + "6")

        Button:
            text: "("
            on_release: expinp._set_text (expinp._get_text() + "( ")


    BoxLayout:
        orientation: 'horizontal'

        Button:
            text: "7"
            on_release: expinp._set_text (expinp._get_text() + "7")

        Button:
            text: "8"
            on_release: expinp._set_text (expinp._get_text() + "8")
                  
        Button:
            text: "9"
            on_release: expinp._set_text (expinp._get_text() + "9")

        Button:
            text: ")"    
            on_release: expinp._set_text (expinp._get_text() + " )")
