
<Introscreen> :
    BoxLayout:
        orientation: 'vertical'
        Video:
            source: "intro_vid.mp4"    
            state: 'play'
            size_hint: 1, 0.9

        BoxLayout:
            orientation: 'horizontal'
            adaptive_height: True
            size_hint: 1, 0.1
            
            Button:
                text: "Quit"
                background_color: "red"
                on_release : app.Quit()
                
            Button:
                text: "Continue"
                on_release: app.root.current = "Apphome"


<TextInput> :
    background_color : "#555555"
    cursor_color : "white"
    foreground_color : "white"

<Button>:
    font_size: 20

<Button> :
    background_color: "#555555"

<Mainscreen> :    
    id: MS
    Accordion:
        selected_color: (0.8,0,1,1)
        background_color: (0.8,0,1,1)
        color: "red"
        orientation: 'horizontal'
        AccordionItem:
            title: 'Scientific'
            BoxLayout:
                orientation: 'vertical'
                padding: 5
                background_color : "#FF0055"

                Label:
                    text: "AK Sharma Programs"
                    color:"#3333FF"
                    height: dp(10)
                    size_hint: 1, 1
                    font_size: 25

                BoxLayout:
                    orientation: "horizontal"
                    TextInput:
                        id: Sciep
                        hint_text:"ex : 2+3*4"
                        size_hint: 0.8, 1
                        height: dp(7)

                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.2, 1
                        Button:
                            text: "="
                            size_hint: 1, 0.5
                            height: dp(7)
                            on_release: app.calculate(Sciep._get_text())
                        Button:
                            text:  "C"
                            size_hint: 1, 0.5
                            on_release: Sciep._set_text ("")

                BoxLayout:
                    orientation: 'horizontal'

                    Button:
                        text: "sin"
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + "sin")

                    Button:
                        text: "cos"
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " cos")
                            
                    Button:
                        text: "tan"
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " tan ")   

                    Button:
                        text: "pow"    
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " raise to power ")

                BoxLayout:
                    orientation: 'horizontal'

                    Button:
                        text: "+"
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " + ")

                    Button:
                        text: "-"
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " - ")
                            
                    Button:
                        text: "÷"
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " ÷ ")   

                    Button:
                        text: ")"    
                        size_hint: 0.5,1
                        on_release: Sciep._set_text (Sciep._get_text() + " )")
                BoxLayout:
                    orientation: 'horizontal'

                    Button:
                        text: "1"
                        on_release: Sciep._set_text (Sciep._get_text() + "1")

                    Button:
                        text: "2"
                        on_release: Sciep._set_text (Sciep._get_text() + "2")
                            
                    Button:
                        text: "3"
                        on_release: Sciep._set_text (Sciep._get_text() + "3")

                    Button:
                        text: "X"
                        on_release: Sciep._set_text (Sciep._get_text() + " X ")

                BoxLayout:
                    orientation: 'horizontal'

                    Button:
                        text: "4"
                        on_release: Sciep._set_text (Sciep._get_text() + "4")

                    Button:
                        text: "5"
                        on_release: Sciep._set_text (Sciep._get_text() + "5")
                            
                    Button:
                        text: "6"
                        on_release: Sciep._set_text (Sciep._get_text() + "6")

                    Button:
                        text: "("
                        on_release: Sciep._set_text (Sciep._get_text() + "( ")


                BoxLayout:
                    orientation: 'horizontal'

                    Button:
                        text: "7"
                        on_release: Sciep._set_text (Sciep._get_text() + "7")

                    Button:
                        text: "8"
                        on_release: Sciep._set_text (Sciep._get_text() + "8")
                            
                    Button:
                        text: "9"
                        on_release: Sciep._set_text (Sciep._get_text() + "9")

                    Button:
                        text: "0"
                        on_release : Sciep._set_text (Sciep._get_text() + "0")

        AccordionItem:
            title: "General"
            BoxLayout:
                orientation: 'vertical'
                padding: 5
                background_color: "#FF0055"

                Label:
                    text: "AK Sharma Programs"
                    color:"#3333FF"
                    height: dp(10)
                    size_hint: 1, 0.3
                    font_size: 25

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, 0.3
                    TextInput:
                        id: expinp
                        font: "orbitron"
                        hint_text:"ex : (2+3)*4-8"
                        size_hint: 0.8, 1
                        height: dp(7)

                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.2, 1
                        Button:
                            text: "="
                            size_hint: 1, 0.5
                            height: dp(7)
                            background_color: "#88ff88"
                            on_release: app.calculate(expinp._get_text())
                        Button:
                            text:  "C"
                            size_hint: 1, 0.5
                            background_color: "#ff5555"
                            on_release: expinp._set_text ("")

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint: 1, 0.2

                    Button:
                        text: "("
                        background_color: "grey"
                        size_hint: 0.5,1
                        on_release: expinp._set_text (expinp._get_text() + "( ")

                    Button:
                        text: "+"
                        background_color: "grey"
                        size_hint: 0.5,1
                        on_release: expinp._set_text (expinp._get_text() + " + ")   

                    Button:
                        text: "-"
                        background_color: "grey"
                        size_hint: 0.5,1
                        on_release: expinp._set_text (expinp._get_text() + " - ")                        

                    Button:
                        text: ")"    
                        background_color: "grey"
                        size_hint: 0.5,1
                        on_release: expinp._set_text (expinp._get_text() + " )")

                    Button:
                        text: "<-"
                        background_color: "#9988ff"
                        size_hint: 0.5, 1
                        on_release: expinp._set_text (expinp._get_text()[: len(expinp._get_text())-1] )
                    
                BoxLayout:
                    orientation: 'horizontal'
                
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.9, 1

                        BoxLayout:
                            orientation: 'horizontal'

                            Button:
                                text: "1"
                                on_release: expinp._set_text (expinp._get_text() + "1")

                            Button:
                                text: "2"
                                on_release: expinp._set_text (expinp._get_text() + "2")
                                    
                            Button:
                                text: "3"
                                on_release: expinp._set_text (expinp._get_text() + "3")


                        BoxLayout:
                            orientation: 'horizontal'

                            Button:
                                text: "4"
                                on_release: expinp._set_text (expinp._get_text() + "4")

                            Button:
                                text: "5"
                                on_release: expinp._set_text (expinp._get_text() + "5")
                                    
                            Button:
                                text: "6"
                                on_release: expinp._set_text (expinp._get_text() + "6")



                        BoxLayout:
                            orientation: 'horizontal'

                            Button:
                                text: "7"
                                on_release: expinp._set_text (expinp._get_text() + "7")

                            Button:
                                text: "8"
                                on_release: expinp._set_text (expinp._get_text() + "8")
                                    
                            Button:
                                text: "9"
                                on_release: expinp._set_text (expinp._get_text() + "9")

                        BoxLayout:
                            orientation: 'horizontal'

                            Button:
                                text: "sqrt"
                                on_release: expinp._set_text (expinp._get_text() + " square root of ")

                            Button:
                                text: "0"
                                on_release: expinp._set_text (expinp._get_text() + "0")
                                    
                            Button:
                                text: "cbrt"
                                on_release: expinp._set_text (expinp._get_text() + " cube root of ")


                    BoxLayout:
                        orientation: 'vertical'
                        size_hint: 0.2, 1
                        
                        Button:
                            text: "pow"    
                            background_color: "grey"
                            on_release: expinp._set_text (expinp._get_text() + " raise to power ")
                            
                        Button:
                            text: "÷"
                            background_color: "grey"
                            on_release: expinp._set_text (expinp._get_text() + " ÷  ")
                    
                        Button:
                            text: "X"
                            background_color: "grey"
                            on_release: expinp._set_text (expinp._get_text() + " X ")
                    
                        Button:
                            text: "."
                            background_color: "grey"
                            on_release: expinp._set_text (expinp._get_text() + ".")